title: Benjamin Brown
description: PhD Student in Mathematics at The University of Edinburgh
baseurl: ''
url: https://bencwbrown.co.uk
permalink: slug
defaults:
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - CNAME
  - screenshot.jpg
  - vendor
plugins:
  - jekyll-sitemap
  - jekyll-font-awesome-sass
strict_front_matter: true
