title: Benjamin Brown's Personal Website
tagline: A personal website outlining my academic interests and other miscellanea.
description: Personal webiste of Benjamin Brown, who is a PhD Student in Mathematics at The University of Edinburgh, specialising in algebraic, complex, and symplectic geometry, along with some mathematical physics.
baseurl: 
url: https://bencwbrown.co.uk
author: Benjamin Brown
twitter:
  username: benjamincwbrown
  card: summary
#facebook:
#  app_id:
#  publisher:
#  admins:
logo: /assets/author.png
social:
  name: Ben Brown
  links:
  - https://facebook.com/TheNotoriousBB
  - https://twitter.com/benjamincwbrown
  - https://github.com/bencwbrown
  - https://linkedin.com/in/bencwbrown
lang: en_GB
permalink: slug
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - CNAME
  - screenshot.jpg
  - vendor
plugins:
  - jekyll-sitemap
  - jekyll-font-awesome-sass
  - jekyll-analytics
  - jekyll-seo-tag
strict_front_matter: true

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-120544103-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
